### ISSUE TITLE
tickets are not working anymore since thursday

### ISSUE THREAD

**Issue by philippfrenzel** [braathen/qv-simple-webticket#2]
Hi,

for a reason that is not really obvious, the ticket system isn't working anymore since thursday ;/ It looks like it has to do with the fact that microsoft patched the badlock issue they had within the smb protocoll..

Do you have the same trouble? Anyone else?

Best Philipp

**Comment by braathen** [comment]
Hi Philipp,

I'm currently at Qonnections, the customer/partner conference and can't really test this, I do find it strange though that a samba patch could impact this. Are you using NTLM as trust perhaps? Will it make any difference if you use IP white lists instead?

**Comment by braathen** [comment]
I did a quick test, NTLM seems affected but using IP whitelists works. Phillipe, can you confirm that it works for you? You need to switch from Windows Authentication to Anonymous on Authenticate.aspx and then add your trusted IP adress to the config.xml file, see the instructions on the first page of this repository. Please let me know how it works for you and/or if you need any help.

**Comment by philippfrenzel** [comment]
Update - we found the issue - since the badlock update, the "All Users" on the local security of a windows machine doesn't apply for domain users, so the access to the file from the ticket user wasn't working anymore! Adding the real domain user who asks for the ticket solved that issue!
